---
- name: Ensure that epel-release is installed
  become: true
  yum:
    name: "epel-release"
    state: present

- name: Ensure that support packages are installed
  become: true
  yum:
    name: "{{ packages }}"
    state: present

- name: Install awscli, force upgrade
  pip: 
    name: awscli
    state: latest

- name: Add jenkins to docker group
  user:
    name: jenkins
    shell: /bin/bash
    groups: docker
    state: present

- name: Restart docker & jenkins after group addition            
  systemd:
    state: restarted
    enabled: yes
    name: "{{ item }}"
  with_items:
    - 'docker'
    - 'jenkins'
